Use case-sensitive path on `import` to resolve CI error.
TravisCI throws the following error:

```
Cannot find module './Pubsub' from 'Store.js'

However, Jest was able to find:

  'Store/Store.js'

You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js'].

See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
```